### ISSUE TITLE
Compilation error: unmappable character for encoding UTF8

### ISSUE THREAD

**Issue by lduivenbode** [nsip/SIF3DMGenerator-Java#1]
**Ubuntu 14.04.3 / Oracle JDK 1.8.0_60**

_SIF3DMGenerator/sif3Datamodel/src/sif/dd/au30/model/StudentSDTNType.java:22: error: unmappable character for encoding UTF8_

_SIF3DMGenerator/sif3Datamodel/src/sif/dd/au30/model/TimeTableSubjectType.java:21: error: unmappable character for encoding UTF8_

**Comment by joerghuber** [comment]
Updated XSD which was the core of the issue. Re-Genarted POJOs and submitted corrected version.
