### ISSUE TITLE
Please add release for this software

### ISSUE THREAD

**Issue by opoudjis** [nsip/SIF3DMGenerator-Java#5]
As discussed in today's HITS meeting, we will need to enforce release management for all software dependencies of HITS, so we can keep track of what functionality is being made publicly available.

There has not been a release of this software since 2015, but it is still being updated. If this is a HITS software dependency, please add a release now and for all HITS releases where this software has been updated. If this is not a HITS software dependency, please consider adding releases anyway.

**Comment by joerghuber** [comment]
There is no HITS dependency on that. It is a simple tool developers can use to generate the a SIF Data Model library based on an XSD. While the framework uses that tool to create a data model library it still has no direct dependency. However I can create a release for it :-).

**Comment by joerghuber** [comment]
Done. I base lined it to v1.0.

**Comment by opoudjis** [comment]
Thank you!
